export const houses = [
  {
      "id": "5a05e2b252f721a3cf2ea33f",
      "name": "Gryffindor",
      "mascot": "lion",
      "headOfHouse": "Minerva McGonagall",
      "houseGhost": "Nearly Headless Nick",
      "founder": "Goderic Gryffindor",
      "members": [
          "5a0fa648ae5bc100213c2332",
          "5a0fa67dae5bc100213c2333",
          "5a0fa7dcae5bc100213c2338",
          "5a107e1ae0686c0021283b19",
          "5a10944f3dc2080021cd8755",
          "5a10947c3dc2080021cd8756",
          "5a1096b33dc2080021cd8762",
          "5a1097653dc2080021cd8763",
          "5a1098fd3dc2080021cd876e",
          "5a109af13dc2080021cd877a",
          "5a109bfc3dc2080021cd877f",
          "5a109c3d3dc2080021cd8780",
          "5a109cb83dc2080021cd8784",
          "5a109cd33dc2080021cd8785",
          "5a109e143dc2080021cd878d",
          "5a109e1e3dc2080021cd878e",
          "5a109e253dc2080021cd878f",
          "5a109e543dc2080021cd8790",
          "5a109f053dc2080021cd8793",
          "5a1226520f5ae10021650d76",
          "5a1226d70f5ae10021650d77",
          "5a12292a0f5ae10021650d7e",
          "5a12298d0f5ae10021650d7f",
          "5a1229e10f5ae10021650d80",
          "5a122cbe0f5ae10021650d89",
          "5a1233ff0f5ae10021650d98",
          "5a1234cb0f5ae10021650d9b",
          "5a1237480f5ae10021650da3",
          "5a1237c00f5ae10021650da5",
          "5a1238070f5ae10021650da6",
          "5a1238350f5ae10021650da7",
          "5a12387a0f5ae10021650da8",
          "5a1238b20f5ae10021650da9",
          "5a1239130f5ae10021650daa",
          "5a12393d0f5ae10021650dab",
          "5a12395f0f5ae10021650dac",
          "5a1239c80f5ae10021650dad",
          "5a1239f10f5ae10021650dae",
          "5a123b450f5ae10021650db7",
          "5a123f130f5ae10021650dcc"
      ],
      "values": [
          "courage",
          "bravery",
          "nerve",
          "chivalry"
      ],
      "colors": [
          "scarlet",
          "gold"
      ]
  },
  {
      "id": "5a05da69d45bd0a11bd5e06f",
      "name": "Ravenclaw",
      "mascot": "eagle",
      "headOfHouse": "Fillius Flitwick",
      "houseGhost": "The Grey Lady",
      "founder": "Rowena Ravenclaw",
      "members": [
          "5a0fa8a6ae5bc100213c233b",
          "5a107ffee0686c0021283b21",
          "5a108023e0686c0021283b22",
          "5a108047e0686c0021283b23",
          "5a1097d53dc2080021cd8769",
          "5a1099cf3dc2080021cd8772",
          "5a109a553dc2080021cd8777",
          "5a109de83dc2080021cd878c",
          "5a109e943dc2080021cd8791",
          "5a109ebd3dc2080021cd8792",
          "5a1225a20f5ae10021650d73",
          "5a12260f0f5ae10021650d75",
          "5a122a880f5ae10021650d82",
          "5a122ac40f5ae10021650d83",
          "5a122aef0f5ae10021650d84",
          "5a12368a0f5ae10021650da0",
          "5a123e450f5ae10021650dc8"
      ],
      "values": [
          "intelligence",
          "creativity",
          "learning",
          "wit"
      ],
      "colors": [
          "blue",
          " bronze"
      ]
  },
  {
      "id": "5a05dc8cd45bd0a11bd5e071",
      "name": "Slytherin",
      "mascot": "serpent",
      "headOfHouse": "Severus Snape",
      "houseGhost": "The Bloody Baron",
      "founder": "Salazar Slytherin",
      "members": [
          "5a0fa6bbae5bc100213c2334",
          "5a0fa6e8ae5bc100213c2335",
          "5a0fa74eae5bc100213c2336",
          "5a0fa772ae5bc100213c2337",
          "5a107e4ae0686c0021283b1a",
          "5a1093eb3dc2080021cd8753",
          "5a10942a3dc2080021cd8754",
          "5a1099353dc2080021cd876f",
          "5a109aa03dc2080021cd8779",
          "5a109d893dc2080021cd8789",
          "5a109d9f3dc2080021cd878a",
          "5a109dab3dc2080021cd878b",
          "5a109f8b3dc2080021cd8795",
          "5a109fa83dc2080021cd8796",
          "5a109fde3dc2080021cd8797",
          "5a1225640f5ae10021650d72",
          "5a1225e30f5ae10021650d74",
          "5a122c200f5ae10021650d88",
          "5a1232600f5ae10021650d93",
          "5a12327c0f5ae10021650d94",
          "5a1233bc0f5ae10021650d97",
          "5a1235060f5ae10021650d9c",
          "5a1236eb0f5ae10021650da1",
          "5a123a710f5ae10021650db1",
          "5a123af40f5ae10021650db5"
      ],
      "values": [
          "ambition",
          "cunning",
          "leadership",
          "resourcefulness"
      ],
      "colors": [
          "green",
          "silver"
      ]
  },
  {
      "id": "5a05dc58d45bd0a11bd5e070",
      "name": "Hufflepuff",
      "mascot": "badger",
      "headOfHouse": "Pomona Sprout",
      "houseGhost": "The Fat Friar",
      "founder": "Helga Hufflepuff",
      "members": [
          "5a0fa11a4d153d00212c47cc",
          "5a0fa360ae5bc100213c232c",
          "5a0fa365ae5bc100213c232d",
          "5a0fa4daae5bc100213c232e",
          "5a0fa842ae5bc100213c2339",
          "5a0fa86dae5bc100213c233a",
          "5a1096253dc2080021cd875f",
          "5a1098bd3dc2080021cd876d",
          "5a109c993dc2080021cd8783",
          "5a1223720f5ae10021650d6f",
          "5a1223ed0f5ae10021650d70",
          "5a122f3d0f5ae10021650d8d",
          "5a1232b10f5ae10021650d95",
          "5a12333f0f5ae10021650d96",
          "5a1234500f5ae10021650d99",
          "5a1235790f5ae10021650d9d",
          "5a123cb40f5ae10021650dbc"
      ],
      "values": [
          "hard work",
          "patience",
          "justice",
          "loyalty"
      ],
      "colors": [
          "yellow",
          "black"
      ]
  }
]

// *******************************

export const characters = [
  {
      "id": "5a0fa648ae5bc100213c2332",
      "name": "Katie Bell",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "Lord Voldemort",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a0fa67dae5bc100213c2333",
      "name": "Cuthbert Binns",
      "role": "Professor, History of Magic",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "ghost"
  },
  {
      "id": "5a0fa7dcae5bc100213c2338",
      "name": "Sirius Black",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Padfoot",
      "animagus": "black dog",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a107e1ae0686c0021283b19",
      "name": "Lavender Brown",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "rat",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a10944f3dc2080021cd8755",
      "name": "Colin Creevey",
      "role": "Student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "muggle-born",
      "species": "human"
  },
  {
      "id": "5a10947c3dc2080021cd8756",
      "name": "Dennis Creevey",
      "role": "Student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "muggle-born",
      "species": "human"
  },
  {
      "id": "5a1096b33dc2080021cd8762",
      "name": "Aberforth Dumbledore",
      "role": "Owner, Hog's Head Inn",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Ab",
      "patronus": "goat",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a1097653dc2080021cd8763",
      "name": "Albus Dumbledore",
      "role": "Headmaster, Hogwarts",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Elder, 15\", thestral tail hair",
      "boggart": "Ariana (sister)",
      "patronus": "phoenix",
      "ministryOfMagic": true,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a1098fd3dc2080021cd876e",
      "name": "Seamus Finnigan",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "banshee",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a109af13dc2080021cd877a",
      "name": "Hermione Granger",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Vine wood, 10 3/4\", dragon heartstring",
      "boggart": "failure",
      "patronus": "otter",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "muggle-born",
      "species": "human"
  },
  {
      "id": "5a109bfc3dc2080021cd877f",
      "name": "Godric Gryffindor",
      "role": "Founder, Hogwarts",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a109c3d3dc2080021cd8780",
      "name": "Rubeus Hagrid",
      "role": "Groundkeeper, Professor, Care of Magical Creatures",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Oak, 16\", unknown core",
      "boggart": "Lord Voldemort",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "half-giant"
  },
  {
      "id": "5a109cb83dc2080021cd8784",
      "name": "Angelina Johnson",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a109cd33dc2080021cd8785",
      "name": "Lee Jordan",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "River",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a109e143dc2080021cd878d",
      "name": "Alice Longbottom",
      "role": "Auror (formerly)",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109e1e3dc2080021cd878e",
      "name": "Frank Longbottom",
      "role": "Auror (formerly)",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109e253dc2080021cd878f",
      "name": "Augusta Longbottom",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109e543dc2080021cd8790",
      "name": "Neville Longbottom",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Cherry, 13\", unicorn hair",
      "boggart": "Severus Snape",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109f053dc2080021cd8793",
      "name": "Remus Lupin",
      "role": "Professor, Defence Against the Dark Arts",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Moony",
      "wand": "Cypress, 10 1/4\", unicorn hair",
      "boggart": "full moon",
      "patronus": "wolf",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "werewolf"
  },
  {
      "id": "5a1226520f5ae10021650d76",
      "name": "Parvati Patil",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "mummy",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1226d70f5ae10021650d77",
      "name": "Peter Pettigrew",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Wormtail",
      "wand": "Chestnut, 9 1/4, dragon heartstring",
      "boggart": "Lord Voldemort",
      "animagus": "rat",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a12292a0f5ae10021650d7e",
      "name": "Harry Potter",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "The Boy Who Lived",
      "wand": "Holly, 11\", phoenix feather",
      "boggart": "dementor",
      "patronus": "stag",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a12298d0f5ae10021650d7f",
      "name": "James Potter I",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Prongs",
      "wand": "Mahogany, 11\", unknown core",
      "patronus": "stag",
      "animagus": "stag",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1229e10f5ae10021650d80",
      "name": "Lily J. Potter",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Willow, 10 1/4\", unknown core",
      "patronus": "doe",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "muggle-born",
      "species": "human"
  },
  {
      "id": "5a122cbe0f5ae10021650d89",
      "name": "Demelza Robins",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1233ff0f5ae10021650d98",
      "name": "Alicia Spinnet",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1234cb0f5ae10021650d9b",
      "name": "Dean Thomas",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "severed hand walking on it's own",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a1237480f5ae10021650da3",
      "name": "Romilda Vane",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1237c00f5ae10021650da5",
      "name": "Arthur Weasley",
      "role": "Head, Misuse of Muggle Artifacts ",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "patronus": "weasel",
      "ministryOfMagic": true,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1238070f5ae10021650da6",
      "name": "William Weasley",
      "role": "Curse Breaker, Gringotts Bank",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Bill",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1238350f5ae10021650da7",
      "name": "Charles Weasley",
      "role": "Dragonologist",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Charlie",
      "wand": "Ash, 12\", unicorn hair tail",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a12387a0f5ae10021650da8",
      "name": "Fred Weasley",
      "role": "co-owner of Weasleys' Wizard Wheezes",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1238b20f5ae10021650da9",
      "name": "George Weasley",
      "role": "co-owner of Weasleys' Wizard Wheezes",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1239130f5ae10021650daa",
      "name": "Ginevra Weasley",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Ginny",
      "patronus": "horse",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a12393d0f5ae10021650dab",
      "name": "Molly Weasley",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "corpses of her family",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a12395f0f5ae10021650dac",
      "name": "Percy Weasley",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1239c80f5ae10021650dad",
      "name": "Ronald Weasley",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Ron",
      "wand": "Willow, 14\", unicorn hair tail",
      "boggart": "Aragog",
      "patronus": "jack russell terrier",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1239f10f5ae10021650dae",
      "name": "Oliver Wood",
      "role": "student",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a123b450f5ae10021650db7",
      "name": "Cadogan",
      "role": "Gryffindor Tower Door Guard",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a123f130f5ae10021650dcc",
      "name": "Nicholas de Mimsy-Porpington",
      "role": "Gryffindor House Ghost",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Nearly Headless Nick",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "ghost"
  },
  {
      "id": "5a0fa8a6ae5bc100213c233b",
      "name": "Terry Boot",
      "role": "student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a107ffee0686c0021283b21",
      "name": "Cho Chang",
      "role": "Student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "patronus": "swan",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a108023e0686c0021283b22",
      "name": "Penelope Clearwater",
      "role": "Student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Penny",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a108047e0686c0021283b23",
      "name": "Michael Corner",
      "role": "Student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a1097d53dc2080021cd8769",
      "name": "Marietta Edgecombe",
      "role": "student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1099cf3dc2080021cd8772",
      "name": "Filius Flitwick",
      "role": "Professor, Charms",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "Lord Voldemort",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "part-goblin"
  },
  {
      "id": "5a109a553dc2080021cd8777",
      "name": "Anthony Goldstein",
      "role": "student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a109de83dc2080021cd878c",
      "name": "Gilderoy Lockhart",
      "role": "Professor, Defense Against the Dark Arts",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Cherry, 9\", dragon heartstring",
      "boggart": "cornish pixies",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a109e943dc2080021cd8791",
      "name": "Luna Lovegood",
      "role": "student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Loony Lovegood",
      "patronus": "hare",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a109ebd3dc2080021cd8792",
      "name": "Xenophilius Lovegood",
      "role": "Editor, The Quibbler",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Xeno",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1225a20f5ae10021650d73",
      "name": "Garrick Ollivander",
      "role": "Wandmaker",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Hornbeam, 12 3/4\", dragon heartstring",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a12260f0f5ae10021650d75",
      "name": "Padma Patil",
      "role": "student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a122a880f5ae10021650d82",
      "name": "Quirinus Quirrell",
      "role": "Professor, Defence Against the Dark Arts",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Alder, 9\", unicorn hair",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a122ac40f5ae10021650d83",
      "name": "Helena Ravenclaw",
      "role": "Ravenclaw House Ghost",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Grey Lady",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "ghost"
  },
  {
      "id": "5a122aef0f5ae10021650d84",
      "name": "Rowena Ravenclaw",
      "role": "Founder, Hogwarts",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a12368a0f5ae10021650da0",
      "name": "Sybill Trelawney",
      "role": "Professor, Divination",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Hazel, 9 1/2\", unicorn hair",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a123e450f5ae10021650dc8",
      "name": "Myrtle Warren",
      "role": "student",
      "house": "Ravenclaw",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Moaning Myrtle",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "muggle-born",
      "species": "ghost"
  },
  {
      "id": "5a0fa6bbae5bc100213c2334",
      "name": "Phineas Nigellus Black",
      "role": "(Formerly) Headmaster of Hogwarts",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a0fa772ae5bc100213c2337",
      "name": "Regulus Black",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a107e4ae0686c0021283b1a",
      "name": "Millicent Bulstrode",
      "role": "student",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a1093eb3dc2080021cd8753",
      "name": "Crabbe",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a10942a3dc2080021cd8754",
      "name": "Vincent Crabbe",
      "role": "Student",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "Lord Voldemort",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1099353dc2080021cd876f",
      "name": "Marcus Flint",
      "role": "student",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a109aa03dc2080021cd8779",
      "name": "Gregory Goyle",
      "role": "student",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109d893dc2080021cd8789",
      "name": "Bellatrix Lestrange",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Bella",
      "wand": "Walnut, 10 3/4\", dragon heartstring",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109d9f3dc2080021cd878a",
      "name": "Rabastan Lestrange",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109dab3dc2080021cd878b",
      "name": "Rodolphus Lestrange",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109f8b3dc2080021cd8795",
      "name": "Draco Malfoy",
      "role": "student",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Hawthorn, 10\", unicorn hair",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109fa83dc2080021cd8796",
      "name": "Lucius Malfoy",
      "role": "School Governer of Hogwarts",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a109fde3dc2080021cd8797",
      "name": "Narcissa Malfoy",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1225640f5ae10021650d72",
      "name": "Theodore Nott",
      "role": "student",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1225e30f5ae10021650d74",
      "name": "Pansy Parkinson",
      "role": "student",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a122c200f5ae10021650d88",
      "name": "Tom Riddle",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Lord Voldemort",
      "wand": "Yew, 13 1/2\", phoenix feather core",
      "boggart": "his own corpse",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a1232600f5ae10021650d93",
      "name": "Horace Slughorn",
      "role": "Professor, Potions",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Cedar, 10 1/4\", dragon heartstring",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a12327c0f5ae10021650d94",
      "name": "Salazar Slytherin",
      "role": "Founder, Hogwarts",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1233bc0f5ae10021650d97",
      "name": "Severus Snape",
      "role": "Professor, Potions",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "patronus": "doe",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": true,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a1235060f5ae10021650d9c",
      "name": "Andromeda Tonks",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1236eb0f5ae10021650da1",
      "name": "Dolores Umbridge",
      "role": "Head of the Muggle Born Registration Commission",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Birch, 8\", dragon heartstring",
      "patronus": "persian cat",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a123a710f5ae10021650db1",
      "name": "Blaise Zabini",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a123af40f5ae10021650db5",
      "name": "Bloody Baron",
      "role": "Slytherin House Ghost",
      "house": "Slytherin",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "ghost"
  },
  {
      "id": "5a0fa4daae5bc100213c232e",
      "name": "Hannah Abbott",
      "role": "student",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a0fa842ae5bc100213c2339",
      "name": "Amelia Bones",
      "role": "Head, Department of Magical Law Enforcement",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": true,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a0fa86dae5bc100213c233a",
      "name": "Susan Bones",
      "role": "student",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a1096253dc2080021cd875f",
      "name": "Cedric Diggory",
      "role": "Student",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Ash, 12 1/4\", unicorn hair",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1098bd3dc2080021cd876d",
      "name": "Justin Finch-Fletchley",
      "role": "student",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "boggart": "Lord Voldemort ",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a109c993dc2080021cd8783",
      "name": "Helga Hufflepuff",
      "role": "Founder, Hogwarts",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1223720f5ae10021650d6f",
      "name": "Ernest Macmillan",
      "role": "student",
      "house": "Hufflepuff",
      "school": "Hogwarts Academy of Witchcraft and Wizardry",
      "alias": "Ernie",
      "boggart": "Lord Voldemort",
      "patronus": "boar",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": true,
      "deathEater": false,
      "bloodStatus": "pure-blood",
      "species": "human"
  },
  {
      "id": "5a1223ed0f5ae10021650d70",
      "name": "Minerva McGonagall",
      "role": "Professor, Transfiguration",
      "house": "Gryffindor",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "wand": "Fir, 9 1/2\", dragon heartstring",
      "boggart": "Lord Voldemort",
      "patronus": "cat",
      "animagus": "tabby cat",
      "ministryOfMagic": true,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human"
  },
  {
      "id": "5a122f3d0f5ae10021650d8d",
      "name": "Newton Scamander ",
      "role": "Author, Fantastic Beasts and Where to Find Them",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Newt ",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1232b10f5ae10021650d95",
      "name": "Hepzibah Smith",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a12333f0f5ae10021650d96",
      "name": "Zacharias Smith",
      "role": "student",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1234500f5ae10021650d99",
      "name": "Pomona Sprout",
      "role": "Professor, Herbology",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "human"
  },
  {
      "id": "5a1235790f5ae10021650d9d",
      "name": "Nymphadora Tonks",
      "role": "Auror",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "alias": "Tonks",
      "patronus": "wolf",
      "ministryOfMagic": true,
      "orderOfThePhoenix": true,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "half-blood",
      "species": "human (metamorphmagus)"
  },
  {
      "id": "5a123cb40f5ae10021650dbc",
      "name": "Fat Friar",
      "role": "Hufflepuff House Ghost",
      "house": "Hufflepuff",
      "school": "Hogwarts School of Witchcraft and Wizardry",
      "ministryOfMagic": false,
      "orderOfThePhoenix": false,
      "dumbledoresArmy": false,
      "deathEater": false,
      "bloodStatus": "unknown",
      "species": "ghost"
  }
]

// const findMembers = (houses, characters) => {
//   let members = []

//   houses.forEach(house =>{
//     house.members.forEach(member => {
//       characters.forEach(character => {
//         if (member === character.id) {
//           members.push(character)
//         }
//       })
//     })
//   })
//   return members
// }

// export const members = findMembers(houses, characters)